nsg.tf, variables.tf
Current `public-network-apptier` network security group:
Changes from this list:
- no idea what's the `52.177.106.146` IP correspond to, not found in Azure public IPS, nor in `az vm list-ip-addresses | grep 52.177.106.146` and nor in any @jenkins-infra repositories: rule set aside from this PR
- no idea for `52.202.51.185` too, kept as one of the whitelisted rsyncd inbound IPs
Ref: https://github.com/jenkins-infra/helpdesk/issues/3257
=> feat: add `prod-jenkins-public-vnet-apptier` Network Security Group

vnets.tf, vpn.tf
This PR should not change anything: the `privatek8s-tier` subnet was imported in the azure-net's state with the command 
```shell
terraform import 'azurerm_subnet.privatek8s_tier' '/subscriptions/dff2ec18-6a8e-405c-8e45-b7df7465acf0/resourceGroups/private/providers/Microsoft.Network/virtualNetworks/private-vnet/subnets/privatek8s-tier'
```
(edit) internal renaming of the subnet data-tier. Used the command
```
terraform state mv 'azurerm_subnet.data_tier' 'azurerm_subnet.private_vnet_data_tier'
```
to avoid destroy/create.
=> feat: migrate definition of the subnet privatek8s-tier in the private vnet from jenkins-infra/azure

dns.tf, locals.tf, main.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3091, this PR adds a DNS zone and associated Azure Service Principal and permissions to allow requesting Let's Encrypt certificates with DNS challenge from the (private) AWS VM hosting trusted.ci.jenkins.io.
=> feat(dns) add letsencrypt DNS support for trusted.ci.jenkins.io 

dns.tf, main.tf
This reverts commit 77267a9de6afb28ea54085db1823ed1e6d6a0aba.
Now that the terraform's Service Principal [are granted the "Application Developer" role](https://github.com/jenkins-infra/terraform-states/commit/a671b2063bfbe41055dbee5fffb69430ed4d9827) (ref. https://github.com/jenkins-infra/azure-net/pull/30#discussion_r1070178697), the creation of new Azure AD application should work.
https://github.com/jenkins-infra/terraform-states/commit/a671b2063bfbe41055dbee5fffb69430ed4d9827
=> Revert "hotfix(dns) use existing Azure AD application for Let's Encrypt instead of managing it(s)"

vnets.tf
Enabling this endpoint so the privatek8s subnet can be added to the prodjenkinsinfra keys vault allowed networks, in order for infra.ci.jenkins.io to access secrets to control and admin other clusters.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2844
=> feat(privatek8s): enable KeyVault service endpoint

vnets.tf
Needed to fix the following error encountered on https://github.com/jenkins-infra/azure/pull/266
> Resource Name: “publick8s-endless-ghoul”): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=“VnetSubnetMissingIPv6AddressSpace” Message=“IPv6 address space required on subnet for dual-stack clusters.”
=> fix: set IPv6 address range for public vnet and publick8s subnet

dns.tf
As noted in [the terraform provider doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_cname_record), CNAME record resource can target either a record or an existing resource.
I chose to target the record `public.publick8s.jenkins.io` as we can't specify multiple resources as target, and as there are two corresponding resources: [an A record and an AAAA record](https://github.com/jenkins-infra/azure/blob/30e3c37e967ae31ca125769a9ee39fe81e99f131/publick8s.tf#L119-L135).
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351 & https://github.com/jenkins-infra/helpdesk/issues/2752
=> feat: add `repo.azure` CNAME record

vnets.tf
Having this dedicated subnet for release.ci.jenkins.io nodes on privatek8s cluster will allow us to finely restrict access to the `prodreleasecore` Azure key vault.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2844
=> feat(private-vnet): add subnet dedicated to the release nodes of privatek8s

dns.tf, locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3337, follows-up #48
This PR adds the required Azure resources to allow cert.ci.jenkins.io certificate generation with Letsencrypt and Azure DNS.
- A new DNS zone cert.ci.jenkins.io, child of jenkins.io is added (same method as for trusted.ci)
- Please note that an apex record is required for `cert.ci.jenkins.io`. For now the IP is defined "raw". The record should be defined in https://github.com/jenkins-infra/azure/blob/main/cert.ci.jenkins.io.tf
- The same set of Azure AD, Service principal, AD password and permissions to the new child zone only
- Please note that `locals.tf` has been changed to hold the expiration date:
- Each SP password will have its own expiration date
- An empty expiration date means: "use a managed …
=> feat(dns/letsencrypt) add AD app, SP and DNS resources for `cert.ci.jenkins.io`

vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2981, this PR adds 2 subnets for ci.jenkins.io:
- No NSG, expecting to define them in https://github.com/jenkins-infra/azure/blob/main/ci.jenkins.io.tf as the rules would be application-specifics
- The agent subnet allows for ~500 IPv4 (current subnet is ~250 so it's a 2x). No need for IPv6 as far as we can tell.
- The controller subnet is "large" (`/24`) to avoid calculation issues (the `10.245.4.x` is reserved). It also allows IPv6 private address to anticipate a public IPv6 for ci.jenkins.io (ref. https://github.com/jenkins-infra/helpdesk/issues/62 and https://github.com/jenkins-infra/helpdesk/issues/3227)
The goal is to start spinning up VM agents for ci.jenkins in these new subnets, closer to the artifact caching proxy, and …
=> feat(vnets) add 2 public subnets for ci.jenkins.io agents and controller

dns-records.tf
This PR imports existing CNAME records from the jenkins.io DNS zone.
I've manually lowered their TTL in order to prepare their target switch from prodpublick8s public-nginx address to publick8s public-nginx address.
=> chore(jenkins.io): import `javadoc` and `wiki` CNAME records

dns-records.tf, dns.tf
This PR imports resources related to `jenkinsistheway.io` in order to prepare the migration of the corresponding service to publick8s.
The existing A record pointing to `prodgw-publick8s` (public IP: 52.167.253.43) in Azure Portal doesn't respond:
```
$ dig jenkinsistheway.io
; <<>> DiG 9.10.6 <<>> jenkinsistheway.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26233
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;jenkinsistheway.io.            IN      A
;; AUTHORITY SECTION:
io.                     1800    IN      SOA     a0.nic.io. hostmaster.donuts.email. 1684255726 7200 900 1209600 3600
;; Query time: 798 msec
;; SERVER: …
```
=> chore(jenkinsistheway.io): import resource group & DNS zone to create a CNAME record instead of a A record

dns-records.tf
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/3938 & #69 
This PR switch the `javadoc` CNAME target from `prodpublick8s` to `publick8s`.
Tested locally by adding `20.119.232.75 javadoc.jenkins.io` to my /etc/hosts.
=> feat(jenkins.io): change `javadoc` CNAME target from `prodpublick8s` to `publick8s`

dns-records.tf
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/3940, #70 & https://github.com/jenkins-infra/azure-net/commit/43fc1f5db9fafb7836af6c6932802eea9540ff6e
This PR switch the `@` (apex) A record target from `prodpublick8s` IPv4 to `publick8s` IPv4 and IPv6.
Tested locally by adding `20.119.232.75 jenkinsistheway.io` to my /etc/hosts.
Note: since a CNAME record can't be `@` or empty, we're keeping an A record for this one.
=> feat(jenkinsistheway.io): change A record target from `prodpublick8s` IP to `publick8s` IPv4 & IPv6

dns-records.tf
Fix the error caused by #72 
> Error: creating/updating DNS A Record “@” (Zone “[jenkinsistheway.io](http://jenkinsistheway.io/)” / Resource Group “proddns_jenkinsisthewayio”): unexpected status 400 with response: {“code”:“BadRequest”,“message”:“The provided ip address ‘2603:1030:408:7::44’ is not valid.“
=> fix(jenkinsistheway.io): add an AAAA record pointing to `publick8s` IPv6

dns-records.tf
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/3945 & #69 
This PR switch the `wiki` CNAME target from `prodpublick8s` to `publick8s`.
Tested locally by adding `20.119.232.75 wiki.jenkins.io` to my /etc/hosts.
=> feat(jenkins.io): change `wiki` CNAME target from `prodpublick8s` to `publick8s`

vnets.tf
First step of https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1557561704
(edited after review)
We tried to create a new PostgreSQL instance named `public-data` in the new `public-vnet` network in https://github.com/jenkins-infra/azure/pull/356 but discovered Flexible Server product does not support IPv6 virtual network (error below when creating the new instance):
```
Flexible Server Name: "public-data"): polling after Create: Code="IPV6AddressSpaceNotSupportedForVnet" Message="The virtual network public-vnet has IPv6 address space which is currently not supported. Please try with a different virtual network that has only IPv4 address space."
```
So this PR creates a distinct IPv4-only  virtual network, with a delegated subnet for postgres. This virtual network is …
=> feat: add a public-db virtual net to host flexible postgres instances

vnets.tf
This PR was tested manually and allows:
- Access to the new `public-db` PgSql database from the private  and public net (https://github.com/jenkins-infra/helpdesk/issues/3486)
- Access to the new `publick8s` cluster (https://github.com/jenkins-infra/helpdesk/issues/3351) and the new ci.jenkins.io VM(s) (https://github.com/jenkins-infra/helpdesk/issues/3535)
Each peering need to be defined by 2 terraform resources (from each side), otherwise it ends up in "Initiated" state with no routing at all
=> feat(vnets) ensure VNet peerings are properly defined for each combination public/public-db/private

dns-records.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1562482092, this PR migrate the keycloak `admin.accounts` record to the new cluster.
Blocked by https://github.com/jenkins-infra/azure/pull/363 (as the DNS `A` record for `private.publick8s` is needed)
=> feat(dns) migrate admin.accounts record from prodpublick8s to the publick8s

dns-records.tf, dns.tf
When https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1564291354 was done (cleanup of former resources for `wiki.jenkins.io  application in `prodpublick8s`), we discovered that the former `wiki.jenkins-ci.org` DNS record was still pointing to the `prodpublick8s` CNAME.
We fixed manually the record to ensure a quick recovery but this PR puts it as code
=> feat(dns) import jenkins-ci.org records already migrated to publick8s

dns-records.tf
To be merged after https://github.com/jenkins-infra/kubernetes-management/pull/4025/
=> feat(jenkins.io): change `uplink` CNAME target from `prodpublick8s` to `publick8s`

dns-records.tf
To be merged after https://github.com/jenkins-infra/kubernetes-management/pull/4028, can be reviewed already.
Note: instead of removing the previously completed `moved` block like I intended in #92, I'll reuse it instead from service to service until all of them are migrated, then I'll remove this block at the end.
=> feat(jenkins.io): change `reports` CNAME target from `prodpublick8s` to `publick8s`

dns-records.tf
To be merged after https://github.com/jenkins-infra/kubernetes-management/pull/4030, can be reviewed already.
=> feat(jenkins.io): change `accounts` CNAME target from `prodpublick8s` to `publick8s`

vnets.tf
This PR adds the Storage service endpoint so the cluster can access restricted storage accounts.
Follow-up of https://github.com/jenkins-infra/azure/pull/385#issuecomment-1577251779
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
=> feat(vnet): add Storage service endpoint to `publick8s-tier` subnet 

dns-records.tf
This PR temporary redirects https://accounts.jenkins.io and https://accounts.jenkins-ci.org to the LDAP migration status announcement https://status.jenkins.io/issues/2023-06-08-ldap-migration-to-publick8s/ while migrating the LDAP service, to ensure no write could happen to the LDAP while allowing ldap.jenkins.io continuing to respond to other services depending on it.
In draft until 12:00 UTC today cf the announcement.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
=> chore(dns-record): change `accounts` CNAME records targets to `status.jenkins.io`

dns-records.tf
Follow-up of #98 
On Netlify, domain alias added to status.jenkins.io project:
=> chore(dns-record): change accountapp CNAME records target to status.jenkins.io Netlify origin domain

dns-records.tf
This PR changes the `ldap` A record target to point from the previous LB IP of `prodpublick8s` cluster to the LB IP of `publick8s` created as code in https://github.com/jenkins-infra/azure/pull/402
In draft until the maintenance has progressed.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
=> feat(jenkins.io): change `ldap` A record target from `prodpublick8s` LB IP to `publick8s` LB IP

dns-records.tf
Sanity checks OK, reverts jenkins-infra/azure-net#101 to restore accounts.jenkins(-ci).com(org)
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
=> Revert "chore(dns-record): change accountapp CNAME records target to status.jenkins.io Netlify origin domain"

dns-records.tf
Follow-up of #86 
With `azure-net` infra.ci.jenkins.io job disabled, ran the following command locally to execute the import:
```console
$ terraform import 'azurerm_dns_cname_record.jenkinsciorg_target_public_publick8s["mirrors"]' /subscriptions/dff2ec18-6a8e-405c-8e45-b7df7465acf0/resourceGroups/proddns_jenkinsci/providers/Microsoft.Network/dnsZones/jenkins-ci.org/CNAME/mirrors
```
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1586969797
=> chore(dns-records): import `mirrors.jenkins-ci.org` CNAME record

dns-records.tf, locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3635, this PR creates the CNAME record as described by Fastly to renew the jenkins.io apex TLS certificate.
=> feat(DNS) add CNAME record for Fastly ACME validation for jenkins.io apex

dns-records.tf
This PR follows up #114. It imports 3 existing ACME DNS (CNAME) records for Fastly.
=> feat(DNS) import Fastly's jenkins.io ACME record

dns-records.tf
Follow up of #113 and #115 this PR imports the existing DNS records in the `jenkins.io` for Fastly-served websites.
The 5 existing DNS records points to the same destination hence the `for_each` form.
=> feat(DNS) add Fastly CNAME records 

dns-records.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3688, this PR removes the managed DNS record from this repository in favor of https://github.com/jenkins-infra/azure/blob/58e52440a4ba252afb140064a0667fafebe6d4fc/cert.ci.jenkins.io.tf#L62-L68 
(otherwise both projects are competing to control this record and its value).
=> cleanup(dns-records) remove cert.ci.jenkins.io record (managed in jenkins-infra/azure)

dns-records.tf, locals.tf
This PR adds this A record which will be used as common of CNAMEs redirecting to the `doks-public` cluster. (Similar to the `public.publick8s` A record)
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649
=> feat: add `doks-public-public-ipv4-address` A record

dns-records.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3748, this PR removes the `acme` challenge static DNS `TXT` record used to manage TLS certificate for `jenkins.io` by fastly.
Please note the diff should not show anything as the record was removed manually: the PR is only to avoid recreating it later
=> fix(DNS) remove fastly-managed acme challenge for jenkins.io

.terraform.lock.hcl, nsgs.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3753
This PR updates tooling to use `trivy` instead of `tfsec`
=> chore: migrate from tfsec to trivy

dns.tf
Following the creation of a DNS zone in DigitalOcean in https://github.com/jenkins-infra/digitalocean/pull/161 for the subdomain `do.jenkins.io`, this PR creates the required `NS` records in Azure to delegate DNS resolution for this domain.
(edited) The following DNS records created manually will have to be removed from once the NS records are propagated:
- `repo.do` (already existing in the new zone)
- `_acme-challenge.repo.do` (we use HTTP-01 for now on `doks-public`)
=> feat(DNS) delegate `do.jenkins.io` to DigitalOcean DNS zone

dns.tf
This PR removes the NS record corresponding to the initial `cloudflare.jenkins.io`, since deleted.
Follow-up of https://github.com/jenkins-infra/cloudflare/pull/10
=> chore(updates.jenkins.io): remove `cloudflare.jenkins.io` NS record

dns-records.tf
This PR defines the existing `CAA` DNS records for `jenkins.io` and `jenkins-ci.org`.
These records have been imported in the terraform state. Merging this PR will apply the following changes (only add tags to the records):
```
~ resource "azurerm_dns_caa_record" "jenkins_caa" {
id                  = "/subscriptions/<redacted>/resourceGroups/proddns_jenkinsci/providers/Microsoft.Network/dnsZones/jenkins-ci.org/CAA/@"
name                = "@"
~ tags                = {
+ "purpose"    = "Jenkins user authentication service"
+ "repository" = "jenkins-infra/azure-net"
+ "scope"      = "terraform-managed"
}
}
~ resource "azurerm_dns_caa_record" "jenkins_caa" {
id                  = "/subscriptions/<redacted>/resourceGroups/proddns_jenkinsio/providers/Microsoft.Network/dnsZones/jenkins.io/CAA/@" …
```
=> feat(DNS) import existing CAA records for jenkins.io and jenkins-ci.org

dns-records.tf
This PR adds CAA record for `westeurope.cloudflare` so CloudFlare can (hopefully) generate an Edge Certificate for its `westeurope.cloudflare.jenkins.io` zone (currently stuck in "pending validation")
Corresponding doc: https://developers.cloudflare.com/ssl/edge-certificates/caa-records/#caa-records-added-by-cloudflare
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649
=> feat(updates.jenkins.io): add CAA record for `westeurope.cloudflare.jenkins.io`

locals.tf, main.tf, vpn.tf
Twin of of https://github.com/jenkins-infra/digitalocean/pull/165
This PR is a first try at sharing a set common values across our terraform projects.
A new [data-only Terraform module](https://developer.hashicorp.com/terraform/language/modules/develop/composition#data-only-modules) has been added in the jenkins-infra/shared-tools to hold the shared values: https://github.com/jenkins-infra/shared-tools/commit/36589078701232007dbdf8b5034fd93901d072c3.
The following changes are introduced to the vpn VM:
- Use "IP" instead of CIDR mask for firewall rules
- Update current SSH inbound admin IPs to the shared list
💡 Notes:
- This module, for now, only specify a set of outputs providing the shared data to projects. It may provide data sources (Azure DNS zones or network ids?) in the future if …
=> chore: use shared admins from shared-tools module

dns.tf
This warning messages started since https://github.com/hashicorp/terraform-provider-azuread/releases/tag/v2.44.0.
It's mainly a renaming of the attributes which helps to avoid confusion between `id`, `object_id`, `client_id` and `application_id` (not mentioning `application_object_id` 🤣 )
=> chore(infra.ci) fix depreciation messages from the `azuread` provider

dns-records.tf
as it only responds with HTTP/404 despite pointing to `stats.jenkins.io`.
It's due to how GitHub Pages handles incoming requests: only 1 level of subdomain is allowed.
=> cleanup(DNS) remove stats.jenkins-ci.org 

providers.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1814901484
This PR adds a resource group and a public vnet within the new (sponsored) subscription).
- The new vnet as a `/14 IPv4 only (no IPv6 for now as we don't have the need... yet).
=> feat: add the public vnet for the secondary (sponsored) subscription

vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3818
This PR adds 2 new resources to allow ci.jenkins.io to spin up VM agents in the new "public-jenkins-sponsorship" VNET:
- Peering between the `public` vnet and this new vnet to ensure controller and agents can communicate with each other without requiring a public IP (agent -> controller is OK for ci.jenkins.io because it is a public service but using private IP for agents is a requirement so the controller should be able to contact these private VMs).
- Also required for VPN to reach the new public subscription network for now
- Add a subnet in the new vnet for ci.jenkins.io agents. Same sizing as the current one: max 512 IPs in the subnet (a BOM build is 300 agents, an ATH build is ~20 agents)
=> feat(vnets) add peering and subnet to allow ci.jenkins.io to spawn VM agents in the new subscription

dns-records.tf
This PR adds two CNAME records for the contributors website, one for serving the original content, the other for Fastly CDN.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
=> feat: add contributors website CNAME records

vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1831970571
Twin of https://github.com/jenkins-infra/azure-net/pull/175 scoped to cert.ci.jenkins.io.
This PR adds the required network resources to allow cert.ci.jenkins.io to spin up ephemeral agents in the new subscription.
This PR is expected to create 5 new resources:
* A resource group
* A vnet and its subnet (2) for cert.ci agents
* Peerings from/to cert.ci existing vnet (2 resources)
=> feat(cert.ci.jenkins.io) add network resources in the secondary (sponsored) subscription

vnets.tf
Description to be added
This PR fixes the network overlaps and add a second subnets.
Applied locally and merged without checks (as changing address spaces in networks must be done through Azure portal UI to avoid bad surprises)
=> fix(vnets) correct CIDR overlaps in the secondary subscription networks + add 2nd subnet for infra.ci packer builds

gateways.tf
In order to restrict the Azure SAS tokens and Cloudflare R2 tokens to only trusted.ci agents, we need to use the existing NAT gateways for trusted.ci but on the [new sponsorship networks]() to keep outbound IP the same.
Same for cert.ci of course.
This PR imports the existing gateways (removed from terraform management but not deleted in jenkins-infra/azure in https://github.com/jenkins-infra/azure/pull/567)
- Need to (manually) migrate the resources in the vnet RGs instead of controller RGs (it was a mistake I did when setting up these NAT gateways)
- Need to import (manually) the resources
Note: For a subsequent PR: opportunity to create a module to avoid repetition and as such make it easy to spin up NAT gateway for public and private networks.
=> feat(vnets) import existing NAT gateways for cert and trusted networks

gateways.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1874074475
This PR adds a NAT gateway for both trusted.ci and cert.ci sponsorship networks to ensure the same outbound IP over time (even if it is a second IP)
=> feat(gateways) add NAT gateways for sponsorships

Jenkinsfile_k8s, versions.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3823
=> chore: use terraform `1.6` instead of `1.1`

gateways.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3908, this PR adds 2 new NAT gateways, associated with the 2 AKS clusters.
The goal is to have implicit NAT gateway for outbound connection from the AKS cluster subnets which will take precedence over the outbound LB (as changing the cluster to explicit NAT gateway would re-create the cluster which we might not want).
Source: https://www.danielstechblog.io/preventing-snat-port-exhaustion-on-azure-kubernetes-service-with-virtual-network-nat/
=> feat(gateways) add NAT gateways for the publick8s and privatek8s clusters

gateways.tf
As per https://github.com/jenkins-infra/helpdesk/issues/3908#issuecomment-1906084976, this PR associates the `private_outbound` NAT gateway to the `privatek8s` cluster's subnet to use it as the main outbound link.
=> feat(gateways) add a NAT gateway to privatek8s for outbound requests

gateways.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3908
This PR links all private subnets we added manually during the NAT gateway tests.
=> feat(gateways) add all privatek8s operational subnets

gateways.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3908
This is a twin of https://github.com/jenkins-infra/azure-net/pull/199 but for `publick8s`.
Note that the NAT gateway public IP has been added to `publick8s` API allow-list (AKS self-management), along with the `privatek8s` (kubernetes-management + terraform azure)
=> feat(gateways) use NAT gateway for outbound connections on publick8s

vnets.tf
As part of https://github.com/jenkins-infra/helpdesk/issues/3913, we had to reach the new controller VM through VPN, which requires vnet level routing (otherwise VPN cannot hop across 2 peerings). There might be solutions using remote gateway on the first peering hop, but let's add direct peering and we'll see (as not a lot of data transfer is expected)
=> fix(vnets) required peering for VPN to reach the new controller VM

gateways.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3913
The goal is to have the new VM for ci.jenkins.io controller (in the sponsorship subscription) to use the NAT gateway for outbound (same as agents, same IP, already allowed in the LDAP for instance)
=> feat(gateways) setup ci.jenkins.io sponsorship controller subnet to use NAT gateway

gateways.tf
Note the scope is **only** the VM agents and packer VMs for infra.ci.jenkins.io, there is no reason to add this NAT gateway's IPs to any allow-list.
To be revisited if need be but not the case now.
=> feat(gateways) ensure infra.ci sponsorship agents uses a common NAT gateway

updatecli/scripts/dateadd.sh, updatecli/scripts/datediff.sh, updatecli/updatecli.d/letsencrypt_cert.ci.yaml, updatecli/updatecli.d/letsencrypt_trusted.ci.yaml
provide an automatic way to update expiration date for renewing certificates, this will spawn PR to generate the new certificates
=> chore(updatecli): add an updatecli manifest to automatically create a PR to renew certificates for trusted.ci and cert.ci

vnets.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
to plan network separation
=> feat(privatek8s): create dedicated subnet for controllers infra.ci and release.ci

gateways.tf, outputs.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4029
This PR requires https://github.com/jenkins-infra/shared-tools/pull/145 to be able to work. It will be kept as a draft until resolved.
It introduces 2 new additional outbound public IPs to the NAT gateway used by the trusted.ci.jenkins.io agents. The goal is to spread the request to the DockerHub across 3 IPs to avoid triggering the anti-abuse.
Docker told us that we usually make peaks of 2200 req / min when releasing a Docker image (inbound agent): that would make them see around 740 req / min instead (see issue for more details)
Note: billing consideration: these additional IPs are billed but in the Azure account where we have sponsor credits. It won't increase the usual Azure account bill (paid by CDF).
----
Once merged, …
=> feat(gateways) spread trusted.ci agents outbound trafic to 3 IPs instead of 1

dns-records.tf
This PR adds two CNAME records for the versioned docs website, one for serving the original content, the other for Fastly CDN.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
=> feat: add docs website CNAME records

gateways.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4069
When we [migrated infra.ci.jenkins.io to `arm64`](https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624), we [created a dedicated controller subnet](https://github.com/jenkins-infra/azure-net/pull/220) but we forgot to associate this subnet to the NAT gateway, resulting in using the LB (with SNAT) method for outbound connections instead of NAT gateway.
This PR corrects this by adding the subnet to the collection.
=> fix(gateways) add missing infra.ci agents subnet to use NAT gateway instead SNAT for outbound method

gateways.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4059
This PR aims at avoiding HTTP/429 errors on Chocolatey when building packer images in infra.ci.
=> feat(gateways) add a second outbound IP to infra.ci agents/packers to spread outbound load

gateways.tf, vnets.tf
This PR adds a new subnet to support the new cluster described in https://github.com/jenkins-infra/helpdesk/issues/2649.
Notes:
- As per the [proposed network sizing](https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2096296286), the subnet is only a `/24` as we don't expected more than ~200 nodes and pods will have their own private CIDR.
- Note we can grow this subnet for now if needed (vnet is a `/14` so we still have plenty of available ranges)
- The NAT gateway is not yet associated: it looks like the custom module does not like specifying a non existing subnet. I've opened https://github.com/jenkins-infra/azure-net/pull/233 for this when the subnet will be created
=> feat(vnets) add a new subnet for the ci.jenkins.io agents 1 AKS cluster

gateways.tf, vnets.tf
Blocked by #234
This PR ensures that the subnet (sponsored subscription) are ready to handle the new AKS cluster for ci.jenkins.io container agents with the following changes:
- Using a NAT gateway for outbound connections (requires the subnet to be created) as specified in https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2096296286
- Add a secondary public IP for outbound to spread the workload (and avoid potential HTTP/429 from DockerHub)
=> feat(gateways) prepare ci.jenkins.io vnet for more agents (AKS)

dns-records.tf, locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3954, this PR removes the leftover DNS records pointing to removed resources in DigitalOcean
=> cleanup(DNS records) remove Digital Ocean Kubernetes cluster DNS records

.gitignore, Jenkinsfile_k8s, locals.tf, outputs.tf, vnets.tf
Experiment related to https://github.com/jenkins-infra/helpdesk/issues/4114
It serves as a test case for https://github.com/jenkins-infra/pipeline-library/pull/862.
It introduces a new "local file" which replaces (**non sensitive**) outputs. This local file is in JSON and we want to publish it on each terraform apply on the main branch to reports.jenkins.io.
The goal is to automate the data extraction to a centralized place where we will be able to consume it (in this case: to retrieve the outbound IP and add them to the infra API)
=> feat: add report publication from local file to automate jenkins-infra-data extraction

vnets.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3923#issuecomment-2147128098
create network needs for the sponsored kubernetes cluster for infra.ci agents.
=> feat(privatek8s/sponsorship): add infra.ci.jenkins.io kubernetes sponsorship networking (vnet/subnet)

gateways.tf
fix to failure of https://github.com/jenkins-infra/azure/pull/715
Plan: 2 to add, 0 to change, 0 to destroy.
1 json output
2 outbound azurerm_subnet_nat_gateway_association
=> feat(infraci/agents-sponsored/cluster): add new subnet to infra ci outbound ips in sponsored

gateways.tf
Reverts jenkins-infra/azure-net#250
As per https://github.com/jenkins-infra/azure/pull/715#issuecomment-2158813175, we have to rename the subnet, which will re-create it.
First, we need to remove the nat gateway association from the "soon to be deleted because name too long subnet" hence this PR
=> Revert "feat(infraci/agents-sponsored/cluster): add new subnet to infra ci outbound ips in sponsored"

vnets.tf
This PR re-creates the subnet used for the infra.ci.jio Kubernetes agents (ref. ) with a shorter name:
`infra-ci-jenkins-io-sponsorship-vnet-kubernetes-agent` (53 chars) instead of `infra-ci-jenkins-io-sponsorship-vnet-infraci_jenkins_io_kubernetes-agent` (72 chars) to fix the error mentioned inhttps://github.com/jenkins-infra/azure/pull/715#issuecomment-2158813175
Of course it sets the name to a different convention than other subnets, but unless we want to recreate everything we don't have any solution: I chose to only rename the subnet to avoid recreating the whole vnet.
=> hotfix(vnets) shorten name for the infra.ci sponsored subnet used for kubernetes agents

dns-records.tf
This PR adds new.stats CNAME record that will be used for serving the new stats website content.
Note: using "new.stats" subdomain until the corresponding GSoC project is ready to replace the existing stats.jenkins.io
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401
=> feat: add `new.stats` jenkins.io CNAME record

vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3923, this PR enable Azure Network endpoints for KeyVaults and Storage on the subnet used by the infracijio-agents-1 cluster.
Note: we also need to add the parent vnet in the allowed vnets of the keyvault for infra.ci
=> feat(vnets) enable Keyvault and Storage endpoints for infracijio-agents-1 subnet

vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3923
Blocks https://github.com/jenkins-infra/azure/pull/746
Since https://github.com/jenkins-infra/kubernetes-management/pull/5342, the terraform agents are running in a different network which need to access the postgreSQL vnet.
=> hotfix(vnets) add peering between infracijio-agents-1 and public-db

gateways.tf
To avoid PRs such as https://github.com/jenkins-infra/azure-net/pull/231, we want to allow creation of a given subnet in the same change as the NAT gateway association.
This PR applies the changes in https://github.com/jenkins-infra/shared-tools/pull/152 and move resources to avoid any changes.
Requires https://github.com/jenkins-infra/shared-tools/pull/152 to be merged before having a successful plan.
=> fix(gateway) decouple NAT gateways from subnets

gateways.tf
Caught while working on #268 
This PR effectively changes the outbound IP of the release.ci.jenkins.io controller from the `privatek8s`'s LB outbound IPs (`20.22.6.81`) to the `private_vnet` NAT gateway outbound IP (`20.65.63.127`).
No issue expected:
- LDAP is already setup (for infra.ci.jenkins.io) to accept the NAT outbound IP (ref. https://github.com/jenkins-infra/kubernetes-management/blob/187b0bb92620c23f774697ad56d56c51a3925255/config/ldap.yaml#L25C8-L25C20)
=> feat(gateways) set release.ci.jenkins.io controller subnet to use the private outbound gateway (instead of AKS LB)

gateways.tf
as per @daniel-beck information, outbound connexion from cert.ci agents is sometimes unable to join github.com. This new IP will help to spread the load.
Plan: 3 to add, 0 to change, 0 to destroy.
=> feat(cert.ci): add an outbound ip for cert ephemeral agents on sponsored account

gateways.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2262377024
This PR is a short term fix to unblock ci.jenkins.io builds stuck with DockerHub `HTTP/429 toomanyrequests` HTTP errors when pulling images.
=> feat(gateways) increase amount of outbound IPs for ci.jenkins.io agents to spread egress workloads

vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2263339493
This PR ensures that both controller and VM agents (ci.jenkins.io) can access the keyvault through subnet endpoints
=> feat(vnets) allow keyvault endpoint for ci.jenkins.io controller and VM agents

gateways.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4204#issuecomment-2281268067
This PR adds a new subnet dedicated for ACI agents on ci.jenkins.io.
ACI agents are currently using the default network setup, e.g. using a public IP.
As such, they are unable to reach the private ACP.
As per the plugin documentation (see below) using a private IP requires a dedicated subnet with a [delegation](https://learn.microsoft.com/en-us/azure/virtual-network/manage-subnet-delegation?tabs=manage-subnet-delegation-portal) to ACI service.
It means we cannot share the existing subnet used for Azure VM agents: we need a new subnet in the same vnet (to keep using the same NSG and private DNS endpoints).
=> feat(vnets) add a new dedicated subnet for ci.jenkins.io ACI agents

dns-records.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4204
=> cleanup: remove leftovers of the public ACP instance

dns-records.tf, vnets.tf
Prerequisite for the Update Center brownout 1 (see https://github.com/jenkins-infra/helpdesk/issues/2649)
It adds a new `A` DNS record `aws.updates` so it will be easy to defined a `CNAME` pointing to it (and changing the CNAME when needed for brownouts).
It also imports and updates a few existing records.
Notes: 
- Cleanup a non-idempotent change in vnets (delegation) to use the correct action applied by Azure ACI backens
- Import records which are currently defined in jenkins-infra/azure. Need a PR to remove them. Rationale is that using CNAME here ensure operation safety (that is the purpose of the whole repository) of top-level items.
- The plan shows a "removed dot" for the 2 imported records. It's because we used the `FQDN` to populate it. Like the other records in the loop here, …
=> feat(dns) import and add DNS records for updates.jenkins.io

dns-records.tf
This PR switches `stats.jenkins.io` subdomain to the new website, and the old one served from GitHub Pages to `old.stats.jenkins.io`.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4265#issuecomment-2338844499
=> feat: switch `stats.jenkins.io` to the new website

dns-records.tf
Reverts jenkins-infra/azure-net#292
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2343052172
End of the third brownout
=> Revert "feat(DNS records) UC brownout 3: switch to AKS hosted service"

vpn.tf
Since https://github.com/aquasecurity/trivy/blob/main/CHANGELOG.md#0550-2024-09-03 (with https://github.com/jenkins-infra/packer-images/releases/tag/2.1.0) , `trivy` throw false positives.
This PR ignores these errors, along with https://github.com/jenkins-infra/shared-tools/commit/448f09d29e964c0aaef6ef7e9fe272669d09462e
=> chore: fix trivy 0.55.x false positive errors

dns-records.tf
This PR starts the [fourth Update Center brownout](https://www.jenkins.io/blog/2024/09/25/update-center-brownouts-4/) as per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
=> feat(DNS records) switch Update Center to Azure

updatecli/updatecli.d/letsencrypt_cert.ci.yaml, updatecli/updatecli.d/letsencrypt_trusted.ci.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4301#issue-2544767482
This PR improves the PR titles generated by updatecli for expire Azure SP credentials.
We now only include the scope of the PR and the current exp date in the PR title.
=> fix(updatecli): Improve PR titles for Azure SP expired credentials

dns-records.tf
This PR is a preliminary step for https://github.com/jenkins-infra/helpdesk/issues/4366.
It imports the existing record to manage it with Terraform and set its TTL to 60s to anticipate the migration mentioned in the issue.
=> feat(DNS Records) import A lists.jenkins-ci.org and set TTL to 60s

dns-records.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2434782765
This PR reverts https://github.com/jenkins-infra/azure-net/pull/306 to close the fifth brownout for the Update Center.
It should be merged at 10:00am UTC Friday 25 October 2024
=> feat(DNS records) close fifth brownout of the Update Center

outputs.tf
Related to https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/34
This PR fixes the private.vpn outbound ip type to array so there is feature parity with all the outbound ips listed on the azure-net json report.
=> chore(outputs) fixes the private.vpn outbound ip type

dns.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4320
This PR adds NS records for `aws.ci.jenkins.io` subdomain to delegate DNS to Route 53 and ensure the records are always up to date.
Note: a subsequent PR will be requried to keep the route 53 name servers up to date here as I manually cherry picked their values by hand this time
=> feat(DNS) delegate 'aws.ci.jenkins.io' subdomain to AWS route53

dns.tf, updatecli/updatecli.d/aws-dns-ns.yaml
Follow up of #370, related to https://github.com/jenkins-infra/helpdesk/issues/4315
Now that we have a [report](https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json) for the AWS Terraform project (ref. https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/36), we have to track changes made to the Route53 AWS zone for `aws.ci.jenkins.io`.
This is the goal of this PR.
Note: `updatecli` check is expected to fail, but was tested locally with the target's `scmid` atrribute commented out, with success.
=> chore(updatecli/dns) track NS for aws.ci.jenkins.io

dns-records.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3089
- Allow Google Workpasce to send emails to unblock @Wadeck , from https://support.google.com/a/answer/33786?hl=fr&visit_id=638731413171831433-758340368&rd=1#zippy=%2Cexemples-denregistrements-spf
- Set the SPF to `~all` to mark email failing SPF as anti spam (with high score) instead of rejecting
=> feat(dns/jenkins.io) allow google workpace in SPF

gateways.tf, outputs.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4620 and https://github.com/jenkins-infra/helpdesk/issues/4619.
Required by https://github.com/jenkins-infra/azure/pull/975
This PR is a partial revert of #349 with the following changes:
- It only has the "sponsored subscription" related resources.
- The NAT gateway for ci.jenkins.io only has 2 IPs (instead of 4 previously)
- Bugfix on the gateway: it now has an explicit dependency to the module which creates the vnet RG
- Merged outputs for ci.jenkins.io and the associated cijenkinsio-agents-1 cluster since they now have the same set of outbound IPs
=> feat(vnets/gateways) re-create ci.jenkins.io resources in the sponsored subscription

vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619#issuecomment-2769750993
Fixup of #354 
We were missing the "private" -> "public-vnet-sponsorship" part of the peering:
=> fix(vnets) correct peering between private <-> public_sponsorship

vnets.tf
ref. https://github.com/jenkins-infra/helpdesk/issues/4619
Because https://github.com/jenkins-infra/azure/pull/985 failed to deploy with the following error:
```
09:17:39  │ Message: "Validation of network acls failure: SubnetsHaveNoServiceEndpointsConfigured:Subnets public-jenkins-sponsorship-vnet-ci_jenkins_io_controller, public-jenkins-sponsorship-vnet-ci_jenkins_io_agents, public-jenkins-sponsorship-vnet-ci_jenkins_io_kubernetes of virtual network /subscriptions/1311c09f-aee0-4d6c-99a4-392c2b543204/resourceGroups/public-jenkins-sponsorship/providers/Microsoft.Network/virtualNetworks/public-jenkins-sponsorship-vnet do not have ServiceEndpoints for Microsoft.Storage resources configured. Add Microsoft.Storage to subnet's ServiceEndpoints collection before trying to ACL Microsoft.Storage …
```
=> feat(vnets) add `Microsoft.Storage` service endpoints for ci.jenkins.io subnets

vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620
Blocks https://github.com/jenkins-infra/azure/pull/986
We need to keep the `AAAA` DNS records pointing to ci.jenkins.io. As such we need IPv6 address space for the controller subnet
=> feat(vnets) add IPv6 address space to the ci.jenkins.io controller subnet

gateways.tf, vnets.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4250
completing https://github.com/jenkins-infra/azure/pull/997
setting the network for the privatek8s cluster on the sponsored account
`Plan: 17 to add, 0 to change, 0 to destroy.`
=> feat(privatek8s-sponsorship) duplicate network in sponsored account

gateways.tf, vnets.tf
Reverts #360 and #361 as a per-requisite for #362.
Rationale: adding the missing `provider` to an existing set of resources does not destroy the "old" resources in the former subscription (pointed by the default provider). It's a specific behavior when playing around with providers.
As such, this PR reverts the code to mark the resources to be destroyed. Then we'll re-revert in #362
=> cleanup: revert private sponsored vnet

vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2797439659
Fixup of https://github.com/jenkins-infra/azure-net/pull/360
The Azure UI shows the following error in the `private-sponsored-vnet` "Peerings" section:
Syncing has no effect: a popup appears explaining that the counterpart network `private-vnet` does not have any peering enabled to `private-sponsored-vnet`.
This PR aims at fixing this missing element.
=> fix(vnets) add missing peering

vnets.tf
ref. https://github.com/jenkins-infra/helpdesk/issues/4250
This PR adds a missing peering to allow infra.ci agents to reach the `privatek8s_sponsorship` AKS control plane for management (for both terraform and helmfile).
=> feat(vnets) add peering between infra.ci-agents and privatek8s-sponsorship

outputs.tf, vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250
Required for the private ingress setup of `privatek8s-sponsorship` cluster values.
=> chore(outputs) export missing privatek8s-sponsorship network infos

dns-records.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
Blocks https://github.com/jenkins-infra/kubernetes-management/pull/6525
=> feat(dns-records) migrate github-comment-ops to new privtaek8s-sponsorship cluster

vnets.tf
Fix https://github.com/jenkins-infra/azure/pull/1074#issuecomment-2992164913 and anticipate on cert.ci.jenkins.io migrating from the sponsored subscription to the CDF subscription 
Ref. https://github.com/jenkins-infra/helpdesk/issues/4696
=> fix(vnets) enable Microsoft.Storage endpoint for cert.ci.jenkins.io agents subnets

dns.tf, locals.tf, updatecli/updatecli.d/aws-dns-ns.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4688
- AWS DNS zone defined in https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/fed79049d3011a211d0fddc918502cf1a39f5017/ci.jenkins.io.tf#L153-L155
- Updatecli manifest tested locally to update values after reverting #376 . Should fail the check until this PR is merged
=>  feat(dns) delegate `aws.ci.jenkins.io` to AWS Route53 DNS Zone

dns-records.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4727
=> feat(dns-record) add TXT record for lib.jenkins.io to prove Maven Central Ownership

outputs.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4692 and https://github.com/jenkins-infra/helpdesk/issues/4701
=> cleanup(vnets) remove infra.ci and packer networks from the sponsorship subscription

locals.tf, main.tf, vpn.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4765
Also cleans up the admin public IPs
Note: by stopping the usage of the terraform module, we are switching to an updatecli "automated updates" pattern instead.
----
Updatecli check is expected to fail (diff on a remote, not local branch) but was tested locally with success by commenting out the target's `scmid` attributes
=> cleanup: remove leftovers of the decommissioned Azure sponsored subscription and the shared terraform 'infra' module

vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4617
The PR https://github.com/jenkins-infra/azure/pull/1191 failed to apply with TCP `i/o timeout` because infra.ci agents cannot reach the private API of the new `publick8s` cluster.
This change adds peering so this problem won't be there anymore.
=> feat(vnets) add peering between infra.ci and public to allow access to the private AKS API

dns-records.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4617
migrate 
- builds.reports
- contributors.origin
- docs.origin
- plugins-sites-issues
- stats
to the new publick8s
=> feat(dns): migrate some services to the new publick8s (see the list below)

modules/azure-full-vnet/main.tf, modules/azure-full-vnet/variables.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4616
Following up #451, this PR sets the 2 last remaining subnets (delegated to our DBs) to "private" (e.g. disabling the "outbound default method").
=> feat(modules/azure-full-vnet) ensure default outbound method is always disabled (subnets are privates by default)
