jenkins-infra/azure-net

vnets.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/2924

feat: activate peering between vnets

---

locals.tf
vpn.tf

Follow-up of #10 (from this suggestion: https://github.com/jenkins-infra/azure-net/pull/10/files#r1036870452)

fix: less confusing local variable names

---

locals.tf

My current IP address from new ISP

Add mwaite IP address

---

vpn.tf

…
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>

hotfix(vpn) use the same RG for nsg-rules as the associated nsg otherwise it is not visible

---

vnets.tf

Needed for https://github.com/jenkins-infra/azure/pull/260

fix: enable Microsoft.Storage endpoint on privatek8s subnet to manage postgresql

---

vnets.tf

feat: add `publick8s` subnet

---

dns.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3060 & https://github.com/jenkins-infra/helpdesk/issues/2844

feat: add CNAME record for `github-comment-ops` webhook

---

locals.tf
versions.tf
vpn.tf

fix(vpn,private-vpn) ensure that firewall rules order is not changed when adding/removing

---

dns.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3448

feat(dns): add TXT record to verify `jenkins-transfert` GitHub organization

---

dns.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/2844

feat(dns): add CNAME record for `release.ci.jenkins.io` on `privatek8s`

---

dns.tf
main.tf
vnets.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3470
⚠️ DO NOT merge before re-import :
Before import: Plan: 2 to add, 0 to change, 0 to destroy.
After  import : Plan: 0 to add, 1 to change, 0 to destroy. 
change is just tags

feat(cert.ci): import virtual network and subnet for agents

---

dns-records.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1564632990

feat(dns) migrate DNS of incrementals to `publick8s`

---

locals.tf

Twin of https://github.com/jenkins-infra/azure/pull/377
related to https://github.com/jenkins-infra/helpdesk/issues/3613

fix: update puppet.jenkins.io IP for NSGs

---

dns-records.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1586969797

feat(jenkins.io): change `fallback.get`, `get` and `mirrors` CNAME records target from `prodpublick8s` to `publick8s`

---

dns-records.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1586972368

feat(jenkins.io): change `plugin-site-issues` CNAME record target from `prodpublick8s` to `publick8s`

---

dns-records.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1588038925

feat(jenkins.io): change `plugins.origin` CNAME record target from `prodpublick8s` to `publick8s`

---

dns-records.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1588040182

feat(jenkins.io): change `www.origin` CNAME record target from `prodpublick8s` to `publick8s`

---

dns-records.tf

Fixup of #108 
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1588040182

fix(jenkins.io): correct IP target for the apex A record

---

dns-records.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1591316525 and https://github.com/jenkins-infra/helpdesk/issues/3627
This PR only imports the DNS record (first step)

fix(dns) import apex record for jenkins-ci.org

---

dns-records.tf
locals.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3627
and https://github.com/jenkins-infra/helpdesk/issues/3351

feat(dns): change jenkins-ci.org apex to publick8s

---

dns-records.tf
locals.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3227

feat(dns): add AAAA records for `jenkins.io` and `jenkins-ci.org`

---

locals.tf
vnets.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3690

cleanup: removed unused or non-existing resources

---

vnets.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3602
provide a subnet dedicated to use with a flexible mysql database
Plan: 1 to add, 0 to change, 0 to destroy.

feat(public_db_mysql): provide the vnet and subnet for a managed flexible mysql database

---

dns.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/2649

feat: create `cloudflare.jenkins.io` child zone, delegated to CloudFlare

---

dns.tf

Follow-up of #138 
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649

chore(cloudflare): update name servers

---

dns-records.tf

fixup: set CAA on top level

---

vnets.tf

Ref.  https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1831970571
This PR adds the required network resources to allow trusted.ci.jenkins.io to spin up ephemeral agents in the new subscription.
This PR is expected to create 5 new resources:
- A resource group
- A vnet and its subnet (2) for trusted agents
- Peerings from/to trusted existing vnet (2 resources)

feat(vnets) add resource for trusted.ic in the secondary sponsored subscription

---

dns-records.tf

Applied manually as an import was required.
2 records changed as expected.

feat(dns-records) import repo.jenkins-ci.org records and add the godaddy verification value

---

vnets.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1860472394
Twin of https://github.com/jenkins-infra/azure-net/pull/175 scoped to infra.ci.jenkins.io.
This PR adds the required network resources to allow infra.ci.jenkins.io to spin up ephemeral agents in the new subscription.
This PR is expected to create 5 new resources:
* A resource group
* A vnet and its subnet (2) for cert.ci agents
* Peerings from/to cert.ci existing vnet (2 resources)

feat(vnets) add network resources for cert.ci.jenkins.io in the secondary (sponsored) subscription

---

gateways.tf

Follow-up of #187 
Related to https://github.com/jenkins-infra/helpdesk/issues/3875 and https://github.com/jenkins-infra/helpdesk/issues/2649.
This PR migrates gateway resource to a module (added in https://github.com/jenkins-infra/shared-tools/commit/9055b53def6d837e8dbb92d0c1576f5a810d231e)

feat(gateways) migrate to module

---

updatecli/updatecli.d/letsencrypt_cert.ci.yaml

chore(updatecli): correct manifest

---

updatecli/updatecli.d/letsencrypt_cert.ci.yaml
updatecli/updatecli.d/letsencrypt_trusted.ci.yaml

chore(updatecli): update title for PR

---

vnets.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
need at least 29 ips so /27 minimum

fixup(privatek8s/vnet): expand controllers dedicated subnets

---

vnets.tf

fixup(privatek8s/vnet/subnets) expand controller dedicated subnets

---

Jenkinsfile_k8s

This PR is used to test https://github.com/jenkins-infra/pipeline-library/pull/863

chore(pipeline) validate https://github.com/jenkins-infra/pipeline-library/pull/863 and cleanup Pipeline Library tests

---

gateways.tf

Reapply https://github.com/jenkins-infra/azure-net/pull/250
This reverts commit 6c836f258daa92840a56d06af320c1870da06f6f.
Goal: fix https://github.com/jenkins-infra/azure/pull/715#issuecomment-2158809755 error message

Reapply "feat(infraci/agents-sponsored/cluster): add new subnet to infra ci ou…" (#251)

---

outputs.tf

related to https://github.com/jenkins-infra/helpdesk/issues/3923#issue-2102183861
in order to follow change made on the network we need a source of thrust for updatecli in multiple repositories like https://github.com/jenkins-infra/docker-openvpn

chore(output): add vnets to json output file

---

outputs.tf
vnets.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3923
This PR also fixes the outputs

feat(vnets) allow infracijio-agents1 to reach private AKS clusters

---

vnets.tf

following #259 fix provider to sponsorship

hotfix(infraci-sponsorship): fix provider for peering to public sponsorship

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069

feat(dns) switch Update Center back to AWS. End of brownout 1.

---

dns-records.tf

No changes expected (hence the `cleanup` tag)

cleanup(dns-records) remove unused blocks and move CAA records to their own section

---

dns-records.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/2649

feat(dns-records) start UC brownout 2 - (switch to Azure UC)

---

dns-records.tf

Reverts jenkins-infra/azure-net#289
closing UC Brownout 2

Revert "feat(dns-records) start UC brownout 2 - (switch to Azure UC)"

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995

feat(dns-records) close Update Center fourth brownout

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2434782765

feat(dns records) start 5th brownout for UC

---

dns-records.tf

Reverts jenkins-infra/azure-net#312

Revert "feat(dns-records) open 6th Update Center brownout"

---

outputs.tf
vpn.tf

Needed by https://github.com/jenkins-infra/helpdesk/issues/4352 (at least)
Note: this PR also renames the Public IP resource (with a `moved` block to be deleted once applied) to avoid confusion

chore(reports/vpn) add vpn outbound IP to infra report

---

vpn.tf

Uses https://github.com/jenkins-infra/shared-tools/commit/3612af5941ad4f991dd5f731e91c27c1394f0477 (fixup of https://github.com/jenkins-infra/shared-tools/commit/88c2ba77f7a780e6ed06b465d927cf32bde4d410) and extends it to non controller VMs here

fix(vpn) correct user_data calls by providing missing template variable

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/2649

feat(dns-records) switch Update Center to the new Azure implementation

---

dns-records.tf

This PR is a preliminary work for https://github.com/jenkins-infra/helpdesk/issues/4497.
It imports the existing TXT apex records for `jenkins.io` so it can be managed as code.

feat(dns records) import TXT apex for jenkins.io

---

vnets.tf

fix(privatek8s-sponsorship) correct naming to avoid underscore

---

gateways.tf
vnets.tf

following #361  and #360  use the correct provider to install in the sponsorship account

feat(privatek8s-sponsorship) re-create vnet and gateway with proper naming and provider

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516

feat(dns-records) migrate release.ci to new privtaek8s-sponsorship cluster

---

dns-records.tf
gateways.tf
outputs.tf
vnets.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075

cleanup: remove privatek8s network and gateway resources and references

---

locals.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4629

cleanup(dns) remove cert.ci Letsencrypt Azure Application

---

outputs.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4689#issuecomment-2961894408
output the new infos for the vnet

chore(outputs): add infraciagents2 and infra-ci-jenkins-io-vnet to the output report

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4696

feat(dns) add builds.reports DNS record to jenkins.io

---

dns-records.tf

Anticipating on the migration in https://github.com/jenkins-infra/helpdesk/issues/4644

feat(dns-records) import record 'issues' for JIRA and set up TTL to `60`

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4644 (LF ticket IT-28124)

feat(dns-records) add a TLS challenge for LF on the testissue instance

---

outputs.tf
vnets.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4690
privatek8s network

feat(privatek8s): add privatek8s network subnets

---

vnets.tf

Fixup of https://github.com/jenkins-infra/azure-net/pull/414#issuecomment-3108911513
Reported in https://github.com/jenkins-infra/helpdesk/issues/4616#issuecomment-3108932169 to reconsider the exclusion later

fix(vnets) do not associate outbound NAT agteway for VPN

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4690

feat(dns-records) migrate release.ci to Azure CDF susbcription

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4757

feat(dns-records) add ACME challenge for issues.jenkins.io

---

dns-records.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4691

feat(dns-records) add 2 records for staging mirrorbits

---

dns-records.tf
outputs.tf
providers.tf
vnets.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4765

cleanup: remove jenkins-sponsorship provider (aka. sponsored subscription)

---

vnets.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4617#issuecomment-3314747497

feat(vnets) add a new subnet for the new publick8s cluster with no NAT gateway

---

modules/azure-full-vnet/locals.tf
modules/azure-full-vnet/main.tf
modules/azure-full-vnet/outputs.tf
modules/azure-full-vnet/providers.tf
modules/azure-full-vnet/variables.tf
vnets.tf

Preparatory work for https://github.com/jenkins-infra/helpdesk/issues/4616#issuecomment-3314861527
- The vnet module is only used here. Let's keep it in close to avoid testing issues or discrepancies (submodule has been a bad idea for validating module code changes without dangers)

feat(vnets) move module in repo, add default outbound acccess supportfor subnets and set publick8s subnet to private (e.g. no default outbound)

---

dns-records.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/4617#issuecomment-3332342227

feat(dns-records) change cnames to publick8s on the old cluster

---

dns-records.tf
locals.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4617
migrate
- rating
- reports
- uplink
and change the ipv4 and ipv6 for publick8s

feat(dns): migrate rating, reports, uplink to the new publick8s and change the ipv4 and ipv6 for publick8s

---

vnets.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/4616#issuecomment-3348517602

feat(vnets) disable default outbound access method for all subnets except DBs

---

dns-records.tf

as per https://github.com/jenkins-infra/helpdesk/issues/1626#issuecomment-3350796235
change cname to use usage.do.jenkins.io instead of usage.aws.jenkins.io

feat(dns-records) migrate update.jio to digital ocean
